### PR TITLE
Convert from internal JSON parser to Jackson / Backport to Java 1.8

### PR DESCRIPTION
**Pull request by JellyBrick**

### CODE REVIEW

**Comment by alula** [comment]
What's the point of moving to Jackson?

**Comment by alula** [comment]
I also don't like the idea of sticking to ancient Java version and would like to use modern language features.

This could be a good compromise for us: https://github.com/bsideup/jabel

**Comment by JellyBrick** [comment]
> What's the point of moving to Jackson?

- More configurable settings
- POJO mapping (more straightforward)
- High performance (module: Blackbird / Afterburner / etc...)

**Comment by alula** [comment]
I understand benefits of using serialized objects, but I prefer staying with nanojson fork for smaller footprint of the library.

I'm not going to merge this PR, but I like other changes you made so I suggest to make an another PR with J9+ API usage removed, jabel setup to use modern language features and modernized Gradle build file.

**Pull request closed without merging**
